### ISSUE TITLE
Support for FS Edge

### ISSUE THREAD

**Issue by kronn** [ArjenL/vim-kinesis#2]
The Freestyle Edge uses the same syntax for its configuration, but has different file-names.

When I mount the internal v-drive, I see the layouts like this:

```
/media/$USER/FS EDGE/layouts/layout1.txt
...
/media/$USER/FS EDGE/layouts/layout9.txt
```

Do you think you could support those as well?

**Comment by ArjenL** [comment]
The Freestyle Edge (and Pro) use basically the same syntax, but the naming of the action tokens (the keys) are slightly different in some cases, and they also have more action tokens compared to the Advantage2. I'd prefer to make a separate syntax file for the Freestyle Edge/Pro to make typos easier to spot and make it clear that the files of the Advantage2 and Freestyle are incompatible.

But yes, I'll add support for the Freestyle Edge/Pro probably somewhere in the next few weeks, time permitting.

**Comment by kronn** [comment]
That sounds great. No rush, though, I just stumbled over this and wanted to let you know.

**Comment by ArjenL** [comment]
I added Freestyle Pro/Edge layout file support. Try it out and report any bugs if you find them.
